import { jsPDF } from 'jspdf';

export function exportReport({ result, fileName, providerName }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = 210;
  const MARGIN = 18;
  const CONTENT_W = W - MARGIN * 2;
  let y = 20;

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const addPage = () => { doc.addPage(); y = 20; };
  const checkPage = (needed = 10) => { if (y + needed > 280) addPage(); };

  const h1 = (text) => {
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(245, 158, 11);
    doc.text(text, MARGIN, y);
    y += 10;
  };

  const h2 = (text) => {
    checkPage(10);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(241, 241, 243);
    doc.text(text, MARGIN, y);
    y += 7;
  };

  const h3 = (text) => {
    checkPage(8);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 210);
    doc.text(text, MARGIN, y);
    y += 5;
  };

  const body = (text, indent = 0) => {
    checkPage(6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 195);
    const lines = doc.splitTextToSize(text, CONTENT_W - indent);
    doc.text(lines, MARGIN + indent, y);
    y += lines.length * 4.5;
  };

  const divider = () => {
    checkPage(4);
    doc.setDrawColor(42, 42, 58);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, y, W - MARGIN, y);
    y += 4;
  };

  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, W, 297, 'F');

  h1('ATS Scout Analysis Report');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Generated: ${dateStr}  |  File: ${fileName}  |  Provider: ${providerName}`, MARGIN, y);
  y += 8;
  divider();

  h2('ATS Score');
  body(`Before: ${result.ats_score_before}/100   After: ${result.ats_score_after}/100   Delta: +${result.ats_score_after - result.ats_score_before} pts`);
  body(`Authenticity: ${result.authenticity_score}/100`);
  body(`Verdict: ${result.verdict_summary}`);
  y += 4;
  divider();

  h2('HR Perspective');
  const hr = result.hr_perspective;
  body(`Verdict: ${hr.verdict?.toUpperCase()}`);
  body(`First Impression: ${hr.first_impression}`);
  body(hr.reasoning);
  if (hr.strengths?.length) {
    h3('Strengths');
    hr.strengths.forEach(s => body(`✓ ${s}`, 4));
  }
  if (hr.red_flags?.length) {
    h3('Red Flags');
    hr.red_flags.forEach(r => body(`✗ ${r}`, 4));
  }
  y += 4;
  divider();

  h2('Dimension Scores');
  const ds = result.dimension_scores || {};
  Object.entries(ds).forEach(([k, v]) => {
    body(`${k.replace(/_/g, ' ')}: ${v}/100`, 4);
  });
  y += 4;
  divider();

  if (result.ats_missing_keywords?.length) {
    h2('Missing Keywords');
    body(result.ats_missing_keywords.join(', '));
    y += 4;
    divider();
  }

  const required = (result.suggestions || []).filter(s => s.priority === 'required');
  const optional = (result.suggestions || []).filter(s => s.priority === 'optional');

  if (required.length) {
    h2('Required Rewrites');
    required.forEach((s, i) => {
      h3(`#${i + 1} (+${s.impact_points} pts)`);
      body(`BEFORE: ${s.original}`, 4);
      body(`AFTER:  ${s.improved}`, 4);
      body(`Why: ${s.reason}`, 4);
      y += 2;
    });
    divider();
  }

  if (optional.length) {
    h2('Optional Polish');
    optional.forEach((s, i) => {
      h3(`#${i + 1} (+${s.impact_points} pts)`);
      body(`BEFORE: ${s.original}`, 4);
      body(`AFTER:  ${s.improved}`, 4);
      body(`Why: ${s.reason}`, 4);
      y += 2;
    });
    divider();
  }

  checkPage(10);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(75, 75, 90);
  doc.text('Generated by ATS Scout — BYOK, zero servers. Your resume was never uploaded.', MARGIN, y);

  const safeFileName = fileName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const dateTag = now.toISOString().split('T')[0];
  doc.save(`ats-scout-report-${safeFileName}-${dateTag}.pdf`);
}
